spring:
  application:
    name: rent-example

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
